### ISSUE TITLE
自带规则与easylistChina订阅规则冲突无法上网

### ISSUE THREAD

**Issue by zwillhill** [small-5/luci-app-adblock-plus#1]
luci-app-adblock-plus目前似乎分为自带规则和第三方订阅两种
经测试自带规则与easylistChina似乎冲突，会造成无法上网（自带规则随luci-app-adblock-plus的开启强制开启？）
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
关闭luci-app-adblock-plus或移除EasylistChina订阅后网络恢复正常。

自带规则可能已经合并了多项规则，希望自带规则能加上开关或下移至第三方订阅

**Comment by small-5** [comment]
默認啟用就有adblockplus的規則，不要添加這個

**Comment by small-5** [comment]
默認啟動的就是easylistChina，這個規則別再添加了。

**Comment by zwillhill** [comment]
@small-5 请问是否有adguardhome类似的查询日志？尝试在系统自带的DHCP/DNS界面开启了查询日志，但找不到日志位置。
