### ISSUE TITLE
不能git clone源码、需要账号密码

### ISSUE THREAD

**Issue by ihuaer** [small-5/luci-app-adblock-plus#4]
git clone源码时提示输入账号

无法下载源码就不能继承到固件里去

目前是通过手动打包下载

**Comment by VergilGao** [comment]
```git clone https://github.com/small-5/luci-app-adblock-plus package/luci-app-adblock-plus```
理论上来说是没有问题的，因为这个是public的仓库，无需鉴权就可以执行clone

**Comment by small-5** [comment]
大概是他輸錯了，所以才提示要帳號密碼
